{{- if .Values.server.enabled -}}
{{- if .Values.server.ingress.enabled -}}
{{- $serviceName := include "argo-workflows.server.fullname" . -}}
{{- $servicePort := .Values.server.servicePort -}}
apiVersion: {{ include "argo-workflows.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "argo-workflows.server.fullname" . }}
  labels:
   {{- include "argo-workflows.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
    {{- range $key, $value := .Values.server.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.server.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- $kubeVersion := .Capabilities.KubeVersion.GitVersion}}
    {{- range .Values.server.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- if $.Values.server.ingress.paths }}
          {{- range $.Values.server.ingress.paths }}
          {{- include "argo-workflows.ingress.service" (dict "kubeVersion" $kubeVersion "serviceName" .serviceName "servicePort" .servicePort) | nindent 10 }}
          {{- end }}
          {{- end }}
          {{- include "argo-workflows.ingress.service" (dict "kubeVersion" $kubeVersion "serviceName" $serviceName "servicePort" $servicePort) | nindent 10 }}
    {{- end -}}
    {{- with .Values.server.ingress.tls }}
  tls:
      {{- toYaml . | nindent 4 }}
    {{- end -}}
  {{- end -}}
{{- end -}}
