{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "argo-workflows.server.fullname" . }}
  labels:
    {{- include "argo-workflows.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
    app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.server.image.tag | quote }}
  {{- if .Values.server.serviceAnnotations }}
  annotations:
{{ toYaml .Values.server.serviceAnnotations | indent 4}}{{- end }}
spec:
  ports:
  - port: {{ .Values.server.servicePort }}
    {{- if .Values.server.servicePortName }}
    name: {{ .Values.server.servicePortName }}
    {{- end }}
    targetPort: 2746
  selector:
    {{- include "argo-workflows.selectorLabels" (dict "context" . "name" .Values.server.name) | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.server.serviceType }}
  {{- if and (eq .Values.server.serviceType "LoadBalancer") .Values.server.loadBalancerIP }}
  loadBalancerIP: {{ .Values.server.loadBalancerIP | quote }}
  {{- end }}
  {{- if and (eq .Values.server.serviceType "LoadBalancer") .Values.server.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.server.loadBalancerSourceRanges | indent 4 }}{{- end }}
{{- end -}}
