{{- if and .Values.server.enabled .Values.server.createServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "argo-workflows.serverServiceAccountName" . }}
  {{- with .Values.server.serviceAccountAnnotations  }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
{{- end -}}
