{{- if .Values.server.enabled -}}
{{- if .Values.server.ingress.enabled -}}
{{- $serviceName := include "argo-workflows.server.fullname" . -}}
{{- $servicePort := .Values.server.servicePort -}}
apiVersion: {{ include "argo-workflows.ingress.apiVersion" . }}
metadata:
  name: {{ template "argo-workflows.server.fullname" . }}
  labels:
    {{- include "argo-workflows.labels" $ | nindent 4 }}
    {{- range $key, $value := .Values.server.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    {{- range $key, $value := .Values.server.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range .Values.server.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- if $.Values.server.ingress.paths }}
          {{- range $.Values.server.ingress.paths }}
          - backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
          {{- end }}
          {{- end }}
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.server.ingress.tls }}
  tls:
{{ toYaml .Values.server.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
