apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "argo-workflows.controllerServiceAccountName" . }}
  {{ with .Values.controller.serviceAccountAnnotations }}
  annotations:
    {{- toYaml .| nindent 4 }}
  {{- end }}
