apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "argo-workflows.controllerServiceAccountName" . }}
  annotations:
{{ toYaml .Values.controller.serviceAccountAnnotations | indent 4 }}
