{{- if .Values.workflow.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "argo-workflows.fullname" . }}-workflow
{{- if .Values.workflow.namespace }}
  namespace: {{ .Values.workflow.namespace }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "argo-workflows.fullname" . }}-workflow
subjects:
- kind: ServiceAccount
  name: {{ .Values.workflow.serviceAccount.name }}
  {{- if .Values.workflow.namespace }}
  namespace: {{ .Values.workflow.namespace }}
  {{- end }}
{{- end }}
